### PR TITLE
Add table of contents.

### PR DESCRIPTION
**Pull request by hendersonreed**
This was generated using [github-markdown-toc](https://github.com/ekalinin/github-markdown-toc).

This greatly improves navigability, especially on mobile and lets a user skip past categories that don't interest them easily.

### CODE REVIEW

**Comment by rofrol** [comment]
Can you test this https://github.com/tscanlin/tocbot so that we do not have to do this manually?

**Comment by hendersonreed** [comment]
Yep, will do!

**Comment by hendersonreed** [comment]
So, I suppose I'm curious about why you picked tocbot as the solution? GitHub won't execute <script> tags, which as far as I can tell is the easiest way to use tocbot. You could install it as an npm package, but then we don't get much assistance from the package itself, since we still need to do manual work to run the script each time a category is added.

Is there a smarter/easier way to be doing this? I wonder if using some sort of CI service to automatically update the README.md each time a category is added would make any sort of sense. That's probably over-engineered though :)

**Comment by rofrol** [comment]
@hendersonreed I would rather not have to rebuild toc manually, bc sometimes I don't have access to computer, only mobile etc.

I see the alternative is asciidoc https://github.com/isaacs/github/issues/215.

Actual markdown can be converted with

`pandoc -t asciidoc -f markdown README.md > README.asciidoc`

Also mediawiki or rst should support automatic to generation https://github.com/github/markup/issues/904#issuecomment-459218221

Also github wiki https://stackoverflow.com/questions/9721944/automatic-toc-in-github-flavoured-markdown/10771251#10771251

**Comment by rofrol** [comment]
Adding it as is for now. Thanks.

**Pull request merged**
